//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiL.JS {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    Класс ресурса со строгой типизацией для поиска локализованных строк и т. п.
    /// </summary>
    // Этот класс был автоматически создан классом StronglyTypedResourceBuilder
    // с помощью таких средств, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, отредактируйте ResX-файл, а затем повторно запустите программу ResGen
    // с параметром /str или заново постройте ваш проект VS.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Strings() {
        }
        
        /// <summary>
        ///    Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NiL.JS.NetCore.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Переопределяет свойство CurrentUICulture текущего потока для всех
        ///    обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Constructor cannot be static.
        /// </summary>
        public static string ConstructorCannotBeStatic {
            get {
                return ResourceManager.GetString("ConstructorCannotBeStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Do not define a function inside a loop.
        /// </summary>
        public static string FunctionInLoop {
            get {
                return ResourceManager.GetString("FunctionInLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Identifier &quot;{0}&quot; has already been declared.
        /// </summary>
        public static string IdentifierAlreadyDeclared {
            get {
                return ResourceManager.GetString("IdentifierAlreadyDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Can not increment property &quot;{0}&quot; without setter..
        /// </summary>
        public static string IncrementPropertyWOSetter {
            get {
                return ResourceManager.GetString("IncrementPropertyWOSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Can not increment readonly &quot;{0}&quot;.
        /// </summary>
        public static string IncrementReadonly {
            get {
                return ResourceManager.GetString("IncrementReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Invalid left-hand side in assignment..
        /// </summary>
        public static string InvalidLefthandSideInAssignment {
            get {
                return ResourceManager.GetString("InvalidLefthandSideInAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Invalid property name at {0}.
        /// </summary>
        public static string InvalidPropertyName {
            get {
                return ResourceManager.GetString("InvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Unable to process regular expression {0}.
        /// </summary>
        public static string InvalidRegExp {
            get {
                return ResourceManager.GetString("InvalidRegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Method &quot;{0}&quot; can not be called with new keyword.
        /// </summary>
        public static string InvalidTryToCallWithNew {
            get {
                return ResourceManager.GetString("InvalidTryToCallWithNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Method &quot;{0}&quot; can not be called without new keyword.
        /// </summary>
        public static string InvalidTryToCallWithoutNew {
            get {
                return ResourceManager.GetString("InvalidTryToCallWithoutNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Type &quot;{0}&quot; can not be created with new keyword.
        /// </summary>
        public static string InvalidTryToCreateWithNew {
            get {
                return ResourceManager.GetString("InvalidTryToCreateWithNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Type &quot;{0}&quot; can not be created without new keyword.
        /// </summary>
        public static string InvalidTryToCreateWithoutNew {
            get {
                return ResourceManager.GetString("InvalidTryToCreateWithoutNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Too many arguments for function &quot;{0}&quot;.
        /// </summary>
        public static string TooManyArgumentsForFunction {
            get {
                return ResourceManager.GetString("TooManyArgumentsForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Can&apos;t get property &quot;{0}&quot; of &quot;{1}&quot;.
        /// </summary>
        public static string TryingToGetProperty {
            get {
                return ResourceManager.GetString("TryingToGetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Can&apos;t set property &quot;{0}&quot; of &quot;{1}&quot;.
        /// </summary>
        public static string TryingToSetProperty {
            get {
                return ResourceManager.GetString("TryingToSetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Unexpected token.
        /// </summary>
        public static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Unknown identifier &quot;{0}&quot; at {1}.
        /// </summary>
        public static string UnknowIdentifier {
            get {
                return ResourceManager.GetString("UnknowIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ищет локализованную строку, аналогичную Variable &quot;{0}&quot; is not defined.
        /// </summary>
        public static string VariableNotDefined {
            get {
                return ResourceManager.GetString("VariableNotDefined", resourceCulture);
            }
        }
    }
}
